### PR TITLE
RTS-1403/RTS-1272: SHOW CREATE TABLE should not use a clique table for output

### PR DESCRIPTION
**Pull request by hazen**
Most of SQL commands produce a nice table of output.  However, @ph07 would like for the output of the `SHOW CREATE TABLE` command to be simply printed to stdout so the user can easily cut and paste the output.

### CODE REVIEW

**Comment by andytill** [comment]
Looks like this would be easy to extend for the JIRA about queries and create tables that return no results. @gordonguthrie @javajolt

**Comment by hazen** [comment]
@andytill Great Idea adding in support for https://bashoeng.atlassian.net/browse/RTS-1272.  Pretty straightforward.

**Comment by macintux** [comment]
Something seems to be broken:

```riak-shell(3)>create table foo (time timestamp not null, firmware varchar, primary key ((quantum(time, 15, 's')), time));
Table foo successfully created and activated.
riak-shell(4)>show create table foo;                                            UNEXPECTED ERROR - if you have logging on please send your logfile to Basho: Error processing incoming message: error:function_clause:[{riak_ql_to_string, pk_to_sql, [{key_v1, [{hash_fn_v1, riak_ql_quanta, quantum, [{param_v2, [<< time >>], undefined}, 15,s], timestamp}]}], [{file, src/riak_ql_to_string.erl }, {line,137}]}, {riak_ql_to_string, ddl_rec_to_sql,2, [{file, src/riak_ql_to_string.erl }, {line,108}]}, {riak_ql_to_string, ddl_rec_to_sql_multiline, 2, [{file, src/riak_ql_to_string.erl }, {line,117}]}, {riak_ql_show_create_table, show_create_table, 2, [{file, src/riak_ql_show_create_table.erl }, {line,40}]}, {riak_kv_ts_svc, sub_tsqueryreq,4, [{file, src/riak_kv_ts_svc.erl }, {line,486}]}, {riak_api_pb_server, process_message,4, [{file, src/riak_api_pb_server.erl }, {line,388}]}, {riak_api_pb_server, connected,2, [{file, src/riak_api_pb_server.erl }, {line,226}]}, {riak_api_pb_server, decode_buffer,2, [{file, src/riak_api_pb_server.erl }, {line,364}]}]```

**Comment by macintux** [comment]
let's try that without backticks:

riak-shell(3)>create table foo (time timestamp not null, firmware varchar, primary key ((quantum(time, 15, 's')), time));
Table foo successfully created and activated.
riak-shell(4)>show create table foo;                                            UNEXPECTED ERROR - if you have logging on please send your logfile to Basho: Error processing incoming message: error:function_clause:[{riak_ql_to_string, pk_to_sql, [{key_v1, [{hash_fn_v1, riak_ql_quanta, quantum, [{param_v2, [<< time >>], undefined}, 15,s], timestamp}]}], [{file, src/riak_ql_to_string.erl }, {line,137}]}, {riak_ql_to_string, ddl_rec_to_sql,2, [{file, src/riak_ql_to_string.erl }, {line,108}]}, {riak_ql_to_string, ddl_rec_to_sql_multiline, 2, [{file, src/riak_ql_to_string.erl }, {line,117}]}, {riak_ql_show_create_table, show_create_table, 2, [{file, src/riak_ql_show_create_table.erl }, {line,40}]}, {riak_kv_ts_svc, sub_tsqueryreq,4, [{file, src/riak_kv_ts_svc.erl }, {line,486}]}, {riak_api_pb_server, process_message,4, [{file, src/riak_api_pb_server.erl }, {line,388}]}, {riak_api_pb_server, connected,2, [{file, src/riak_api_pb_server.erl }, {line,226}]}, {riak_api_pb_server, decode_buffer,2, [{file, src/riak_api_pb_server.erl }, {line,364}]}]

**Comment by macintux** [comment]
Working on a patch.

**Comment by macintux** [comment]
With that bug fixed, my only concern is the relatively displeasing aesthetic. Wondering how hard it would be to add some brain-dead indenting.

**Comment by macintux** [comment]
Ah, another ugly crash message occurs when asking to show the creation of a non-existent table.

riak-shell(7)>show create table foo3;
UNEXPECTED ERROR - if you have logging on please send your logfile to Basho: Error processing incoming message: error:undef:[{riak_ql_table_foo3_213165988796717733726656492606139898593, get_min_required_ddl_cap,[], []}, {riak_kv_ts_util, is_table_supported,2, [{file, src/riak_kv_ts_util.erl }, {line,689}]}, {riak_kv_ts_util, check_table_feature_supported, 2, [{file, src/riak_kv_ts_util.erl }, {line,672}]}, {riak_api_pb_server, connected,2, [{file, src/riak_api_pb_server.erl }, {line,219}]}, {riak_api_pb_server, decode_buffer,2, [{file, src/riak_api_pb_server.erl }, {line,364}]}, {gen_fsm,handle_msg,7, [{file, gen_fsm.erl }, {line,505}]}, {proc_lib,init_p_do_apply,3, [{file, proc_lib.erl }, {line,239}]}]

**Comment by hazen** [comment]
@macintux The missing table issue is unrelated to this and I *think* there is a change in the works.

**Comment by macintux** [comment]
Since that's being worked on elsewhere: +1

**Comment by macintux** [comment]
...and I retract my approval, because that fix is already in place but we need to extend it, might as well do it here

**Comment by hazen** [comment]
Thinking the fix will actually end up in QL or KV, not riak_shell, but I'll keep you posted

**Comment by macintux** [comment]
+1

**Comment by macintux** [comment]
Forgot thumbs isn't merging, did so manually

**Comment by hazen** [comment]
@macintux It needs two reviewers in order to automagically merge

**Pull request merged**
