### PR TITLE
Update help for TS 1.5 SQL commands

### PR DESCRIPTION
**Pull request by gordonguthrie**

### CODE REVIEW

**Comment by hazen** [comment]
@gordonguthrie Looks like you missed Andy's addition of `SHOW CREATE TABLE`

**Comment by andytill** [comment]
Problem with the original PR?

**Comment by hazen** [comment]
@andytill There were a couple of typos/formatting issues with https://github.com/basho/riak_shell/pull/71. Not sure why GG decided to create a new branch and PR  ¯\_(ツ)_/¯

**Comment by hazen** [comment]
Oh.  I see, he just lumped everything together under `SHOW`

**Comment by andytill** [comment]
lol ok!

**Comment by paegun** [comment]
+1

**Comment by paegun** [comment]
+1

**Comment by korry8911** [comment]
+1

**Pull request merged**
