### PR TITLE
Add support for alter table with properties

### PR DESCRIPTION
**Pull request by macintux**
Full alter table support will come later. This enables changing bucket properties only.

### CODE REVIEW

**Comment by hazen** [comment]
thumbot retry

**Comment by hazen** [comment]
+1

**Comment by paegun** [comment]
+1

**Comment by hazen** [comment]
Builds locally. Not sure why it fails for Thumbs

**Comment by paegun** [comment]
+1

**Comment by davidx** [comment]
@thumbot retry plsthx

**Comment by macintux** [comment]
+1

**Comment by davidx** [comment]
+1

**Comment by davidx** [comment]
Oh, it won't count yours @macintux we'll need @javajolt or @paegun to chime in. thx

**Comment by macintux** [comment]
Does the fact that @javajolt added a commit make a difference? That's why he asked me to +1.

**Comment by hazen** [comment]
+1

**Comment by hazen** [comment]
Excellent question.  I assumed my +1 would not could since I touched it last.

**Comment by davidx** [comment]
@macintux nope, it just ignores the person who created the PR(for purposes of counting reviewers). Doesn't care where the commits come from.

**Comment by davidx** [comment]
@javajolt ^^

**Pull request merged**
